/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shine' at '12/12/15 3:28 AM' with Gradle 2.6
 *
 * @author shine, @date 12/12/15 3:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
